--ao=wasapi
--deband
--deband-grain=0
--deband-iterations=4
--dither-depth=auto
--embeddedfonts=no
--force-window=yes
--gpu-api=vulkan
--hr-seek=no
--hwdec=nvdec-copy
--ignore-path-in-watch-later-config
--loop
--no-border
--no-osd-bar
--osd-border-size=1
--osd-color=0.8
--osd-font-size=16
--osd-margin-x=8
--osd-margin-y=4
--priority=high
--save-position-on-quit
--scale-blur=0.95
--scale=ewa_lanczos
--screen=3
--screenshot-directory=C:\Users\volt\.screenshots\mpv
--screenshot-format=png
--screenshot-high-bit-depth=yes
--screenshot-png-compression=0
--screenshot-template="%f.%wH.%wM.%wS.%wT"
--sub-border-size=1
--sub-color=0.8
--sub-font-size=26
--sub-gray
--sub-margin-x=8
--sub-margin-y=4
--tone-mapping=bt.2446a
--vo=gpu-next
--vulkan-swap-mode=fifo
--watch-later-options-clr
